speed: 4
defaultPosition:
  y: 21
  x: 23

animations:
  idleLookingDownAnimation:
    spritePath:
      - "assets/sprites/player/player_down_2.png"
  idleLookingUpAnimation:
    spritePath:
      - "assets/sprites/player/player_up_2.png"
  idleLookingLeftAnimation:
    spritePath:
      - "assets/sprites/player/player_left_2.png"
  idleLookingRightAnimation:
    spritePath:
      - "assets/sprites/player/player_right_2.png"
  walkingDownAnimation:
    spritePath:
      - "assets/sprites/player/player_down_1.png"
      - "assets/sprites/player/player_down_2.png"
      - "assets/sprites/player/player_down_3.png"
      - "assets/sprites/player/player_down_2.png"
  walkingUpAnimation:
    spritePath:
      - "assets/sprites/player/player_up_1.png"
      - "assets/sprites/player/player_up_2.png"
      - "assets/sprites/player/player_up_3.png"
      - "assets/sprites/player/player_up_2.png"
  walkingLeftAnimation:
    spritePath:
      - "assets/sprites/player/player_left_1.png"
      - "assets/sprites/player/player_left_2.png"
      - "assets/sprites/player/player_left_3.png"
      - "assets/sprites/player/player_left_2.png"
  walkingRightAnimation:
    spritePath:
      - "assets/sprites/player/player_right_1.png"
      - "assets/sprites/player/player_right_2.png"
      - "assets/sprites/player/player_right_3.png"
      - "assets/sprites/player/player_right_2.png"